common/models/User.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface {

//    const STATUS_INACTIVE = 0;
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;
    
    public $password;
    public $repassword;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id) {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null) {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username) {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token) {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
                    'password_reset_token' => $token,
                    'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token) {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId() {
        return $this->getPrimaryKey();
    }
    
    public function getProfileId() {
        return $this->profile_id;
    }
    
    public function getProfile()
    {
        return $this->hasOne(Profile::className(), ['id' => 'profile_id']);
    }
    
    public function getProfileName() {
        return $this->profile->firstname;
    }
        
    public function getRole() {
        return $this->role;
    }
    
    public function getName() {
        return $this->username;
    }
    
    public function getJoinDate() {
        return $this->created_at;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey() {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey) {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password) {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password) {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey() {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken() {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken() {
        $this->password_reset_token = null;
    }

}

frontend/controllers/GradeController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\base\Model;
use common\models\CourseList;
use common\models\CourseListSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\components\AccessRule;
use kartik\widgets\Alert;
use kartik\widgets\Growl;

class GradeController extends \yii\web\Controller {

    public function actionStudent() {
        $studentList = \common\models\Profile::find()->joinWith('user')->where(['user.role' => 3])->asArray()->all();
        $courseList = \common\models\CourseList::find()->asArray()->all();

        return $this->render('student', [
                    'studentList' => $studentList,
                    'courseList' => $courseList,
        ]);
    }

    public function actionReport($studentId,$testId) {
        $student = \common\models\Profile::findOne($studentId);
        $searchModel = new \common\models\AssessmentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['user_course_list.profile_id' => $studentId]);
        $dataProvider->query->andWhere(['user_course_list.id' => $testId]);
        return $this->render('report2', [
                    'student' => $student,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTest($id, $testId) {

        $count = count(\Yii::$app->request->post('Assessment', []));

        $student = \common\models\Profile::findOne($id);
        $instructor = \common\models\Profile::findOne(\Yii::$app->user->id);
        $course = \common\models\CourseList::findOne($testId);
        $questions = \common\models\QuestionBank::findAll(['course_id' => $testId]);
//        var_dump($questions);die();
        foreach ($questions as $question) {
            $models[$question->id] = new \common\models\Assessment();
        }
        if (Model::loadMultiple($models, Yii::$app->request->post()) && Model::validateMultiple($models)) {
            $userCourseList = new \common\models\UserCourseList();
            $userCourseList->profile_id = $id;
            $userCourseList->course_id = $testId;
            $userCourseList->instructor_id = \Yii::$app->user->id;
            $userCourseList->save();
            
            foreach ($models as $model) {
                $model->user_course_list_id = $userCourseList->id;
                $flag = $model->save(false);
            }
            

            if ($flag) {
                \Yii::$app->session->setFlash('success', [
                    'type' => Growl::TYPE_SUCCESS,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-check-sign',
                    'title' => ' Proses BERJAYA',
                    'message' => ' Data berjaya ditambah.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
//                die('success');
//            return $this->redirect(['report',['id'=>$student->id]]);
            } else {
                \Yii::$app->session->setFlash('error', [
                    'type' => Growl::TYPE_DANGER,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-remove-sign',
                    'title' => ' Proses GAGAL.',
                    'message' => ' Data tidak berjaya ditambah.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            }
//            die();
            return $this->redirect(['report', 'studentId' => $student->id,'testId'=>$testId]);
//            return $this->redirect(['report'], ['id' => $student->id]);
        } else {
            return $this->render('test', [
                        'model' => $models,
                        'student' => $student,
                        'instructor' => $instructor,
                        'course' => $course,
                        'questions' => $questions,
            ]);
        }
    }

    public function actionTest3($id, $testId) {

        $student = \common\models\Profile::findOne($id);
        $instructor = \common\models\Profile::findOne(\Yii::$app->user->id);
        $course = \common\models\CourseList::findOne($testId);
        $questions = \common\models\QuestionBank::findAll(['course_id' => $testId]);
//        foreach ($questions as $question) {
//            $model[$question->id] = new \common\models\Assessment;
//        }
        $model = [new \common\models\Assessment];
        if ($model->load(\Yii::$app->request->post())) {
            var_dump($model);
            die();
//            if ($post = \Yii::$app->request->post()) {
//                var_dump($post);die();
////                var_dump($post[2]);
//                $questionNo = 1;
//                foreach ($post as $i=>$value) {
//                    var_dump($value[$i]);die();
//                    $model = new \common\models\Assessment;
//                    $model->question_id = $questionNo;
//                    $model->profile_id = $id;
//                    $model->profile_grade = $value[$i];
//                    var_dump($x +1);
//                }
//            }
//            var_dump($model);
            die();
        }
        return $this->render('test2', [
                    'model' => $model,
                    'student' => $student,
                    'instructor' => $instructor,
                    'course' => $course,
                    'questions' => $questions,
        ]);
    }

    public function actionTest2($id, $testId) {
//        $this->enableCsrfValidation = false;
        $student = \common\models\Profile::findOne($id);
        $instructor = \common\models\Profile::findOne(\Yii::$app->user->id);
        $course = \common\models\CourseList::findOne($testId);
        $questions = \common\models\QuestionBank::findAll(['course_id' => $testId]);
        foreach ($questions as $question) {
            $model[$question->id] = new \common\models\Assessment;
        }
//        var_dump($model[1]->attributes);die();
//        die();
        if (\Yii::$app->request->post()) {

            var_dump(\Yii::$app->request->post());
            die();
//            if ($post = \Yii::$app->request->post()) {
////                var_dump($post[1]);
////                var_dump($post[2]);
////                $questionNo = 1;
////                foreach ($post as $i=>$value) {
////                    var_dump($value[$i]);die();
////                    $model = new \common\models\Assessment;
////                    $model->question_id = $questionNo;
////                    $model->profile_id = $id;
////                    $model->profile_grade = $value[$i];
////                    var_dump($x +1);
////                }
//            }
//            var_dump($model);
            die();
        }
        return $this->render('test2', [
                    'model' => $model,
                    'student' => $student,
                    'instructor' => $instructor,
                    'course' => $course,
                    'questions' => $questions,
        ]);
    }

    public function actionReport2($id) {
//        var_dump($id);die();
        $studentList = \common\models\Profile::find()->joinWith('user')->where(['user.role' => 3])->asArray()->all();
        $courseList = \common\models\UserCourseList::find()->where(['profile_id' => $id])->asArray()->all();


        return $this->render('report', [
                    'studentList' => $studentList,
                    'courseList' => $courseList,
        ]);
    }

    public function actionIndex() {
        $searchModel = new \common\models\UserListSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

}

frontend/views/grade/report.php
<?php
/* @var $this yii\web\View */
//var_dump($studentList);die();
//var_dump($courseList);die();
?>
<div class="row">
    <?php foreach ($courseList as $j => $course) { ?>

        <div class="col-md-10">
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-bullseye"></i>

                    <h3 class="box-title"><?= $course['course_name'] ?></h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <ol>
                        <li>Lorem ipsum dolor sit amet</li>
                        <li>Consectetur adipiscing elit</li>
                        <li>Integer molestie lorem at massa</li>
                        <li>Facilisis in pretium nisl aliquet</li>
                        <li>Nulla volutpat aliquam velit
                            <ol>
                                <li>Phasellus iaculis neque</li>
                                <li>Purus sodales ultricies</li>
                                <li>Vestibulum laoreet porttitor sem</li>
                                <li>Ac tristique libero volutpat at</li>
                            </ol>
                        </li>
                        <li>Faucibus porta lacus fringilla vel</li>
                        <li>Aenean sit amet erat nunc</li>
                        <li>Eget porttitor lorem</li>
                    </ol>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- ./col -->
    <?php } ?>
</div>

frontend/views/grade/report2.php
<?php

use yii\helpers\Html;
use yii\helpers\Inflector;
use kartik\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\models\AssessmentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Inflector::humanize($student->firstname) . ' Assessments Report';
$this->params['breadcrumbs'][] = $this->title;

$title = empty($this->title) ? Yii::t('app', 'Report') : $this->title . ' Report';
?>
<div class="assessment-index">

    <?php Pjax::begin(); ?>            <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'pjax' => true, // pjax is set to always true for this demo
        // set your toolbar
        'toolbar' => [
            ['content' =>
                Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'], ['class' => 'btn btn-success', 'title' => Yii::t('app', 'Create assessment'),])//. ' ' .
            //                Html::a(Yii::t('app', 'Create Categories'), ['create'], ['class' => 'btn btn-success']) //. ' ' .
            //                Html::button('<i class="glyphicon glyphicon-plus"></i>', ['type' => 'button', 'title' => Yii::t('app', 'Add Book'), 'class' => 'btn btn-success', 'onclick' => 'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' ' .
            ],
            '{export}',
            '{toggleData}',
        ],
        // set export properties
        'exportConfig' => [
            'pdf' => ['title' => $this->title],
            'csv' => '{csv}',
            'xls' => '{xls}',
        ],
        'export' => [
            'fontAwesome' => true,
            'target' => '_self',
        ],
        // parameters from the demo form
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        //        'showPageSummary' => true,
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => $this->title,
        ],
        'responsiveWrap' => false,
        'persistResize' => false,
        //        'exportConfig' => $exportConfig,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            //[
            //      'attribute'=>'id',
            //                  //      'hAlign' => 'center', 'vAlign' => 'middle',
            //],
            [
                'attribute' => 'question.question',
                'format' => 'raw',
                'value' => function($model) {
                    if ($model->question->subquestion) {
                        return \yii\helpers\Html::tag('span', $model->question->question . " :  " . $model->question->subquestion);
//                        return \yii\helpers\Html::tag('span', $model->question->question . " : <br> " . \yii\helpers\Html::tag('span', $model->question->subquestion, ['class' => 'pull-right']));
//                        return ;
                    } else {
                        return \yii\helpers\Html::encode($model->question->question);
                    }
                },
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'profile.firstname',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'profile_grade',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'comments',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
//            [
//                'attribute' => 'type',
//                'hAlign' => 'center', 'vAlign' => 'middle',
//            ],
//            [
//                'attribute' => 'status',
//                'class' => 'kartik\grid\BooleanColumn',
//                'trueIcon' => '<span class="label label-success">ACTIVE</span>',
//                'falseIcon' => '<span class="label label-danger">DELETED</span>',
//                'falseLabel' => 'DELETED',
//                'trueLabel' => 'ACTIVE',
//            ],
            //[
            //      'attribute'=>'created_at',
            //                  //      'hAlign' => 'center', 'vAlign' => 'middle',
            //],
            //[
            //      'attribute'=>'created_by',
            //                  //      'hAlign' => 'center', 'vAlign' => 'middle',
            //],
            //[
            //      'attribute'=>'updated_at',
            //                  //      'hAlign' => 'center', 'vAlign' => 'middle',
            //],
            //[
            //      'attribute'=>'updated_by',
            //                  //      'hAlign' => 'center', 'vAlign' => 'middle',
            //],
            [
                'class' => 'kartik\grid\ActionColumn',
                'visible' => Yii::$app->user->isAdmin || Yii::$app->user->isSuperAdmin,
                'template' => '{view}{update}{delete}{recover}',
                'viewOptions' => ['title' => 'View', 'data-toggle' => 'tooltip'],
                'updateOptions' => ['title' => 'Update', 'data-toggle' => 'tooltip'],
                'buttons' => [
                    'recover' => function ($url, $model) {
                        if ($model->status === 0) {
                            return Html::a('<span class="glyphicon glyphicon-refresh"></span>', $url, ['title' => Yii::t('yii', 'Recover'), 'data-toggle' => 'tooltip']);
                        }
                    },
                            'delete' => function ($url, $model) {
                        if ($model->status === 1) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, ['title' => Yii::t('yii', 'Delete'), 'data-toggle' => 'tooltip',
                                        'data-method' => 'post']);
                        }
                    },
                        ],
                    ],
//                    [
//                        'header' => 'Permanent Delete',
//                        'class' => 'kartik\grid\ActionColumn',
//                        'template' => '{delete-permanent}',
//                        'buttons' => [
//                            'delete-permanent' => function ($url, $model) {
//                                return Html::a('<span class="glyphicon glyphicon-trash" style="color:red;"></span>', $url, [
//                                            'title' => Yii::t('yii', 'Permanent Delete'), 'data-toggle' => 'tooltip'
//                                ]);
//                            }
//                                ],
//                                'visible' => Yii::$app->user->isAdmin,
//                            ],
                ],
            ]);
            ?>
            <?php Pjax::end(); ?></div>

frontend/views/grade/student.php
<?php
/* @var $this yii\web\View */
//var_dump($studentList);die();
//var_dump($courseList);die();
?>
<div class="row">
    <div class="col-md-6">
        <div class="box box-solid">
            <div class="box-header with-border">
                <i class="fa fa-users"></i>

                <h3 class="box-title">Student List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <ol>
                    <?php foreach ($courseList as $j => $course) { ?>
                        <li><?= $course['course_name'] ?></li>
                        <ul>
                            <?php foreach ($studentList as $i => $student) { ?>
                                <li><?= kartik\helpers\Html::a($student['firstname'], ['grade/test', 'id' => $student['id'], 'testId' => $course['id']]) ?>
                                <?php } ?>
                        </ul>
                        </li>
                    <?php } ?>
                </ol>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- ./col -->
</div>

frontend/views/grade/test.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
//var_dump($student);die();
//var_dump($course);die();
//var_dump($questions);die();
?>
<div class="row">
    <div class="col-md-10">
        <div class="box box-solid">
            <div class="box-header with-border">
                <i class="fa fa-bullseye"></i>

                <h3 class="box-title"><?= $course->course_name ?></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>STUDENT</th>
                                <th><?= $student->firstname ?></th>
                                <th>SORTIE NO</th>
                                <th><?= $student->id ?></th>
                                <th>UNIT</th>
                                <th><?= $student->unit ?></th>
                            </tr>
                            <tr>
                                <th>INSTRUCTOR</th>
                                <th><?= Yii::$app->user->profileName ?></th>
                                <th>DURATION</th>
                                <th></th>
                                <th>DATE</th>
                                <th><?= date('d-m-Y') ?></th>
                            </tr>
                        </thead>
                    </table>
                    <table class="table table-bordered-black">
                        <thead>
                            <tr>
                                <th rowspan="2">NO</th>
                                <th rowspan="2">EXERCISES</th>
                                <th rowspan="2">GRADE</th>
                                <th rowspan="2">COMMENT</th>
                            </tr>
<!--                            <tr>
                                <th>NO</th>
                                <th>EXERCISES</th>
                                <th>GRADE</th>
                                <th>COMMENT</th>
                            </tr>-->

                        </thead>
                        <tbody>
                            <?php $form = ActiveForm::begin(); ?>
                            <?php foreach ($questions as $i => $question) { ?>
                                <tr>
                                    <td><?= $qno = $i + 1; ?><?php echo $form->field($model[$question->id], "[$question->id]question_id")->hiddenInput(['value' => $question->id])->label(false) ?> </td>
                                    <?php if ($question->subquestion) { ?>
                                        <td><?= $question->question . ' : ' . $question->subquestion; ?><?= $form->field($model[$question->id], "[$question->id]profile_id")->hiddenInput(['value' => $student->id])->label(false) ?></td>
                                    <?php } else { ?>
                                        <td><?= $question->question; ?><?= $form->field($model[$question->id], "[$question->id]profile_id")->hiddenInput(['value' => $student->id])->label(false) ?></td>
                                    <?php } ?>
                                    <!--<td><?= $question->question; ?><?= $form->field($model[$question->id], "[$question->id]profile_id")->hiddenInput(['value' => $student->id])->label(false) ?></td>-->
<!--                                    <td><?=
                                                $form->field($model[$question->id], "[$question->id]profile_grade")->inline()
                                                ->radioList(['1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5], ['separator' => " | "])->label(false)
                                        ?></td>-->
                                    <td><?= $form->field($model[$question->id], "[$question->id]profile_grade")->inline()->radioList(['1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5])->label(false) ?></td>
                                    <td><?= $form->field($model[$question->id], "[$question->id]comments")->textarea(['class' => 'full-width full-height'])->label(false) ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
                <div>
                    <?= Html::a('Cancel', Yii::$app->request->referrer, ['class' => 'btn btn-default']) ?>
                    <?= Html::submitButton($model[$question->id]->isNewRecord ? 'Finish Grade' : 'Update Grade', ['class' => $model[$question->id]->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- ./col -->
</div>